@isTest
public class checkRecursiveTest {
    static testMethod void testName() {
        test.startTest();
        checkRecursive.run = true;
        checkRecursive.runOnce();
        checkRecursive.runOnce1();
        checkRecursive.runOnce2();
        checkRecursive.runOncetrgUpdateAccOppSourceType();
        checkRecursive.runOnceSetofBooks();
        checkRecursive.runOnceFiveFiveDate();
        checkRecursive.runOnceSaleEntity();
        checkRecursive.runOnceEntityafterUpdate();
        checkRecursive.runOnceEntityBeforeUpdate();
        checkRecursive.checkForBatch();
        checkRecursive.setBatchTrue();
        checkRecursive.setBatchFalse();
        test.stopTest();
        
    }
    
}